### ISSUE TITLE
Lots of errors when compiling native("jvm") module, “not meant for this backend” error can disappear

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-js#570] opened 2015-05-28 16:46 UTC
If I compile an empty module with the following module descriptor (modeled after `ceylon.ast.redhat`):
```ceylon
native ("jvm")
module tmp "1.1.1" {
    shared import ceylon.ast.core "1.1.1";
    shared import com.redhat.ceylon.typechecker "1.1.1";
    import ceylon.interop.java "1.1.1";
}
```
I get the following errors:
> error encountered [cannot find module artifact com.redhat.ceylon.typechecker-1.1.1.js
	- dependency tree: tmp/1.1.1 -> com.redhat.ceylon.typechecker/1.1.1] at 4:4-4:55 of module.ceylon
error encountered [Module not meant for this backend: tmp] at 2:7-2:9 of module.ceylon
error encountered [cannot find module artifact ceylon.interop.java-1.1.1.js
	- dependency tree: tmp/1.1.1 -> ceylon.interop.java/1.1.1] at 5:4-5:38 of module.ceylon
3 errors.

I think any errors other than the “Module not meant for this backend” shouldn’t be there.

Even worse: If I copy the `Continue.ceylon` file from `ceylon.ast.redhat` over:
```ceylon
import ceylon.ast.core {
    Continue
}
import com.redhat.ceylon.compiler.typechecker.tree {
    Tree {
        JContinue=Continue
    }
}

"Converts a RedHat AST [[Continue|JContinue]] to a `ceylon.ast` [[Continue]]."
shared Continue continueToCeylon(JContinue \icontinue) {
    return Continue();
}

"Compiles the given [[code]] for a Continue
 into a [[Continue]] using the Ceylon compiler
 (more specifically, the rule for a `continue`)."
shared Continue? compileContinue(String code) {
    if (is JContinue jDirectiveStatement = createParser(code).directiveStatement()) {
        // continueDirective doesn’t contain the semicolon
        return continueToCeylon(jDirectiveStatement);
    } else {
        return null;
    }
}
```
I get the following errors:
> Error: Errors found. Compilation stopped.
Note: Created module tmp/1.1.1
error encountered [type declaration does not exist: 'JContinue'] at 19:11-19:19 of Continue.ceylon
error encountered [could not determine type of function or value reference: 'continueToCeylon'] at 21:15-21:30 of Continue.ceylon
error encountered [parameter type could not be determined: 'continue' of 'continueToCeylon'] at 21:32-21:50 of Continue.ceylon
error encountered [type declaration does not exist: 'JContinue'] at 11:33-11:41 of Continue.ceylon
error encountered [package not found in imported modules: 'com.redhat.ceylon.compiler.typechecker.tree' (add module import to module descriptor of 'tmp')] at 4:7-4:49 of Continue.ceylon
error encountered [function or value does not exist: 'createParser'] at 19:43-19:54 of Continue.ceylon
warning encountered [declaration does not exist: 'JContinue'] at 10:25-10:42 of Continue.ceylon
ceylon compile-js: 7 errors.

The “Module not meant for this backend” error vanished!

**Comment by quintesse** [comment] 2015-05-28 20:11
First I think this is actually two issues in one:

 1. any errors other than the “Module not meant for this backend” shouldn’t be there.

 2. missing “Module not meant for this backend” error

Of which I can't reproduce the second one on the command line. I just get the same errors as the first example and no errors at all from `Continue.ceylon` as it gets ignored because of the faulty module file. So I'm guessing this is a IDE-specific problem, not the JS compiler itself. Could you confirm that @lucaswerkmeister and move the issue there?

**Comment by lucaswerkmeister** [comment] 2015-05-28 20:21
1. I agree, the compiler should just abort immediately once the `native` annotation is seen.
2. Perhaps it’s because of the “Compilation stopped” – it aborts before it gets to print the “wrong backend” error?

And I’m on the CLI.

**Comment by quintesse** [comment] 2015-05-28 20:25
> And I’m on the CLI.

In that case I'm unable to reproduce it with the information given above.

**Comment by lucaswerkmeister** [comment] 2015-05-28 21:20
I can reproduce it with:
```sh
cd /tmp
rm -rf source
mkdir -p source/tmp
cat > source/tmp/module.ceylon << 'EOF'
native ("jvm")
module tmp "1.1.1" {
    shared import ceylon.ast.core "1.1.1";
    shared import com.redhat.ceylon.typechecker "1.1.1";
    import ceylon.interop.java "1.1.1";
}
EOF
echo 'package tmp;' > source/tmp/package.ceylon
ceylon compile-js tmp
cat > source/tmp/Continue.ceylon << 'EOF'
import ceylon.ast.core {
    Continue
}
import com.redhat.ceylon.compiler.typechecker.tree {
    Tree {
        JContinue=Continue
    }
}

"Converts a RedHat AST [[Continue|JContinue]] to a `ceylon.ast` [[Continue]]."
shared Continue continueToCeylon(JContinue \icontinue) {
    return Continue();
}

"Compiles the given [[code]] for a Continue
 into a [[Continue]] using the Ceylon compiler
 (more specifically, the rule for a `continue`)."
shared Continue? compileContinue(String code) {
    if (is JContinue jDirectiveStatement = createParser(code).directiveStatement()) {
        // continueDirective doesn’t contain the semicolon
        return continueToCeylon(jDirectiveStatement);
    } else {
        return null;
    }
}
EOF
ceylon compile-js tmp
```

**Comment by quintesse** [comment] 2015-05-28 22:07
That's what I already had, but I can't reproduce it with that. Maybe because I don't have `ceylon.ast`. Are you able to reproduce it without depending on that?

**Comment by lucaswerkmeister** [comment] 2015-05-28 22:10
Oh, yeah, I suppose it depends on that being published. Same behavior without the `ceylon.ast.core` line though. (I edited the comment above to remove it.)

**Comment by chochos** [comment] 2015-08-24 17:33
Is this still happening?

**Comment by lucaswerkmeister** [comment] 2015-08-24 18:26
With the above script, I’m still getting three errors from the first compile command (two “cannot find artifact”, one “module not meant for this backend”), and four (plus three warnings) from the second one (including an NPE in `GenerateJsVisitor`).

**Comment by chochos** [comment] 2015-10-05 21:07
Compiling the empty module doesn't output anything, so the `module not meant for this backend` is still missing, although I'm not sure that should happen; if you're compiling several modules in one go, ignoring the jvm-only modules seems the right thing to do.

**Comment by chochos** [comment] 2015-10-05 21:46
Actually there is a bug here: I tried to compile a default module and the native module for JVM, and nothing happens if the non-js module is present; everything is ignored instead of just the non-js module.

**Comment by quintesse** [comment] 2015-10-05 22:14
> if you're compiling several modules in one go, ignoring the jvm-only modules seems the right thing to do

If you're specifically mentioning the module on the command line it should definitely give the error. Only if you do something like `ceylon compile-js '*'` should JVM modules be ignored, but the `ModuleWildcardsHelper` already takes care of that for you.

**Comment by chochos** [comment] 2015-10-05 22:16
I specifically mentioned the module on the command line and nothing happened. And I do mean *nothing*, as in the default module (which isn't native) didn't get compiled either

**Comment by quintesse** [comment] 2015-10-05 22:52
I'm not sure I understand, so you typed something like `ceylon compile-js jvmmodule default` and it didn't compile the default module?

**Comment by chochos** [comment] 2015-10-05 22:58
Right.

It does show warnings though, if there are any in the code, but that's it.

**Comment by quintesse** [comment] 2015-10-05 23:20
If I try it a `default.js` file *is* generated but doesn't run correctly.

And I get an error for the JVM module:

    ./source/jvmonly/module.ceylon:1: error: module not meant for this backend: jvmonly
    "Only the JVM compiler should be allowed to compile this"

(the error should be changed but at least it's there)

**Comment by quintesse** [comment] 2015-10-05 23:22
The behaviour is exactly the same in the JVM compiler backend btw

**Comment by quintesse** [comment] 2015-10-06 00:11
Grrr I said "I **think** this fixes" GitHub, you should be able to tell the difference between that and "THis fixes" ;)

**Comment by quintesse** [comment] 2015-10-06 00:12
Anyway, take a look @chochos and @lucaswerkmeister to see if this actually fixes it and if not we reopen.

**Comment by chochos** [comment] 2015-10-06 00:18
Now `ceylon compile-js default x` gives me this:

````
source/x/module.ceylon:1: error: module not meant for this backend: x
native ("jvm")
       ^
````

Cool! The default module was not compile, though.

**Comment by quintesse** [comment] 2015-10-06 00:19
Well , like I said, the JVM compiler does the same. It might not be correct, I don't know, but at least both exhibit the same behaviour :)

And fixing that would be another issue IMO

**Comment by chochos** [comment] 2015-10-06 00:20
Sure. Closing, then.

**Comment by quintesse** [comment] 2015-10-06 00:20
:laughing:

**Closed by chochos** 2015-10-06 00:20 UTC
