### ISSUE TITLE
Dynamically type-casted variables cannot be used to build streams with map()

### ISSUE THREAD

**Issue by renatoathaydes** [ceylon/ceylon-js#635] opened 2015-10-03 15:22 UTC
In this code, I define a small interface to represent a HTML element that has text, then attempt to build a stream of it.

```ceylon
interface HasText {
    shared formal variable String textContent;
}

dynamic {
    {HasText*} textItems;

    dynamic doc = window.parent.document;
    dynamic nodes = doc.getElementsByTagName("A");
    Integer nodesLength = nodes.length;
    textItems = (0..nodesLength-1).map((Integer i) {
        HasText elem = nodes.item(i);
        String oldText = elem.textContent;
        print(oldText);
        return elem;
    });
... 
}
```

This, when run with the Beta Web IDE, throws a type error:

```
Runtime error:
--- TypeError: Expected web_ide_script::run.HasText (new1.ceylon 20:23-20:35)
```

This should work, because If I change the type of the Stream to `{String*}` and build a stream by calling `textContent` on each element, then it does work... so it seems it's a bug in not recognizing a custom type.

**Comment by lucaswerkmeister** [comment] 2015-10-03 15:31
I don’t think that’s a bug. It works if you make `HasText` a dynamic interface: http://trybeta.ceylon-lang.org/?gist=03d6a0375eb1af63442a

**Comment by gavinking** [comment] 2015-10-03 16:13
Right, this is exactly what `dynamic` is for, isn't it.

**Comment by renatoathaydes** [comment] 2015-10-03 16:25
But does that mean it work for `String` because it's treated as a dynamic type?

**Comment by gavinking** [comment] 2015-10-03 17:25
Well strings and numbers are special, because there is a built-in mapping between JS and Ceylon types.

**Comment by chochos** [comment] 2015-10-05 18:18
Indeed, you need to make `HasText` a dynamic interface.

**Comment by FroMage** [comment] 2015-10-14 13:31
Sounds like not a bug, closing.

**Closed by FroMage** 2015-10-14 13:31 UTC
