### ISSUE TITLE
NPE for member class within dynamic block

### ISSUE THREAD

**Issue by Kurremkarmerruk** [ceylon/ceylon-js#501] opened 2015-02-05 10:41 UTC
When attempting this code:
~~~Ceylon
shared void run() {
	
	dynamic {
		dynamic hapi = require("hapi");
		dynamic server = \iHapi.Server();
		
		...
	}
	
}
~~~
, the `Server` member class of variable `\iHapi` is annotated with this error in the IDE:
~~~
GenerateJsVisitor caused an exception visiting QualifiedTypeExpression node: java.lang.NullPointerException at unknown
~~~

**Comment by chochos** [comment] 2015-02-05 18:45
This is at compile time? Can't reproduce it, even before the change for #500 this compiles OK.

**Comment by Kurremkarmerruk** [comment] 2015-02-05 23:52
Yeah I am only seeing this annotated in the IDE.  The call to `\iHapi` is a different reference from the `hapi` of the previous line and so the `Server` member class's parent is undefined. 

Shouldn't this give a `Function or value does not exist: \iHapi` or is that not possible in dynamic blocks?

**Comment by chochos** [comment] 2015-02-06 04:33
No, in dynamic blocks we let you call undeclared stuff. I suppose what you really need to do is call `hapi.\iHapi.Server()` but the weird part is that you get an error at compile time, not runtime. The IDE does not have the latest JS compiler so maybe that bug will be gone next time they update the jars.

**Comment by chochos** [comment] 2015-02-12 20:27
Is this still an issue?

**Comment by chochos** [comment] 2015-03-17 17:54
Can't reproduce; closing.

**Closed by chochos** 2015-03-17 17:54 UTC
Labels: bug
